spring:
  datasource:
    url: jdbc:mysql://localhost:3308/recycledb?serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password: 1234
  application:
    name: recycle
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 864000000 # cambiarlo, son muchos dias
      refresh-token:
        expiration: 6048000000 # cambiarlo, son muchos


server:
  port: 8088
  servlet:
    context-path: /api/v1/
springdoc:
  default-produces-media-type: application/json



